# Base image 설정
FROM node:18-alpine

RUN apk add --no-cache libc6-compat

# COPY
COPY . /app

# 작업 디렉토리 설정
WORKDIR /app

# 애플리케이션 종속성 설치
RUN npm install -g yarn
RUN yarn

# 환경변수
ARG NEXT_PUBLIC_API_MOCKING \
NEXT_PUBLIC_SITE_URL \
NEXT_PUBLIC_SERVER \
NEXT_PUBLIC_MOYA_SERVER \
NEXT_PUBLIC_TOKEN \
NEXT_PUBLIC_ACCESS_TOKEN_MAXAGE \
NEXT_PUBLIC_WISE_AI_URL \
NEXT_PUBLIC_WISE_TOKEN \
NEXT_PUBLIC_OPENAI_KEY \
NEXT_PUBLIC_DEMO_ACCOUNT

ENV NEXT_PUBLIC_API_MOCKING=$NEXT_PUBLIC_API_MOCKING \
NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL \
NEXT_PUBLIC_SERVER=$NEXT_PUBLIC_SERVER \
NEXT_PUBLIC_MOYA_SERVER=$NEXT_PUBLIC_MOYA_SERVER \
NEXT_PUBLIC_TOKEN=$NEXT_PUBLIC_TOKEN \
NEXT_PUBLIC_ACCESS_TOKEN_MAXAGE=$NEXT_PUBLIC_ACCESS_TOKEN_MAXAGE \
NEXT_PUBLIC_WISE_AI_URL=$NEXT_PUBLIC_WISE_AI_URL \
NEXT_PUBLIC_WISE_TOKEN=$NEXT_PUBLIC_WISE_TOKEN \
NEXT_PUBLIC_OPENAI_KEY=$NEXT_PUBLIC_OPENAI_KEY \
NEXT_PUBLIC_DEMO_ACCOUNT=$NEXT_PUBLIC_DEMO_ACCOUNT

# 애플리케이션 빌드
RUN yarn build

# 앱 실행 명령어
CMD ["yarn", "start"]