name: Docker Build And Push
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  build:
    name: docker build
    if: github.repository == 'Ryan-TheLion/TripleA-FrontEnd' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build And Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_TAG }}
          build-args: |
            NEXT_PUBLIC_API_MOCKING=${{ secrets.NEXT_PUBLIC_API_MOCKING }}
            NEXT_PUBLIC_SITE_URL=${{ secrets.NEXT_PUBLIC_SITE_URL }}
            NEXT_PUBLIC_SERVER=${{ secrets.NEXT_PUBLIC_SERVER }}
            NEXT_PUBLIC_MOYA_SERVER=${{ secrets.NEXT_PUBLIC_MOYA_SERVER }}
            NEXT_PUBLIC_TOKEN=${{ secrets.NEXT_PUBLIC_TOKEN }}
            NEXT_PUBLIC_ACCESS_TOKEN_MAXAGE=${{ secrets.NEXT_PUBLIC_ACCESS_TOKEN_MAXAGE }}
            NEXT_PUBLIC_WISE_AI_URL=${{ secrets.NEXT_PUBLIC_WISE_AI_URL }}
            NEXT_PUBLIC_WISE_TOKEN=${{ secrets.NEXT_PUBLIC_WISE_TOKEN }}
            NEXT_PUBLIC_OPENAI_KEY=${{ secrets.NEXT_PUBLIC_OPENAI_KEY }}
            NEXT_PUBLIC_DEMO_ACCOUNT=${{ secrets.NEXT_PUBLIC_DEMO_ACCOUNT }}
            NEXT_PUBLIC_JWT_VERIFY_SECRET=${{ secrets.NEXT_PUBLIC_JWT_VERIFY_SECRET }}
            NEXT_PUBLIC_STIBEE_ID=${{ secrets.NEXT_PUBLIC_STIBEE_ID }}
            NEXT_PUBLIC_STIBEE_KEY=${{ secrets.NEXT_PUBLIC_STIBEE_KEY }}
